//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("BD_DSDModel", "FK_Vuelo_Aerolinea", "Aerolinea", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(wsRest.Aerolinea), "Vuelo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(wsRest.Vuelo), true)]
[assembly: EdmRelationshipAttribute("BD_DSDModel", "FK_Vuelo_Ciudad", "Ciudad", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(wsRest.Ciudad), "Vuelo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(wsRest.Vuelo), true)]
[assembly: EdmRelationshipAttribute("BD_DSDModel", "FK_Vuelo_Ciudad2", "Ciudad", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(wsRest.Ciudad), "Vuelo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(wsRest.Vuelo), true)]

#endregion

namespace wsRest
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class BD_DSDEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto BD_DSDEntities usando la cadena de conexión encontrada en la sección 'BD_DSDEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public BD_DSDEntities() : base("name=BD_DSDEntities", "BD_DSDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BD_DSDEntities.
        /// </summary>
        public BD_DSDEntities(string connectionString) : base(connectionString, "BD_DSDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BD_DSDEntities.
        /// </summary>
        public BD_DSDEntities(EntityConnection connection) : base(connection, "BD_DSDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Aerolinea> Aerolineas
        {
            get
            {
                if ((_Aerolineas == null))
                {
                    _Aerolineas = base.CreateObjectSet<Aerolinea>("Aerolineas");
                }
                return _Aerolineas;
            }
        }
        private ObjectSet<Aerolinea> _Aerolineas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Ciudad> Ciudads
        {
            get
            {
                if ((_Ciudads == null))
                {
                    _Ciudads = base.CreateObjectSet<Ciudad>("Ciudads");
                }
                return _Ciudads;
            }
        }
        private ObjectSet<Ciudad> _Ciudads;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Vuelo> Vueloes
        {
            get
            {
                if ((_Vueloes == null))
                {
                    _Vueloes = base.CreateObjectSet<Vuelo>("Vueloes");
                }
                return _Vueloes;
            }
        }
        private ObjectSet<Vuelo> _Vueloes;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Aerolineas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAerolineas(Aerolinea aerolinea)
        {
            base.AddObject("Aerolineas", aerolinea);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Ciudads. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCiudads(Ciudad ciudad)
        {
            base.AddObject("Ciudads", ciudad);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Vueloes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToVueloes(Vuelo vuelo)
        {
            base.AddObject("Vueloes", vuelo);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_DSDModel", Name="Aerolinea")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Aerolinea : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Aerolinea.
        /// </summary>
        /// <param name="coAerolinea">Valor inicial de la propiedad CoAerolinea.</param>
        /// <param name="noRazonSocial">Valor inicial de la propiedad NoRazonSocial.</param>
        public static Aerolinea CreateAerolinea(global::System.String coAerolinea, global::System.String noRazonSocial)
        {
            Aerolinea aerolinea = new Aerolinea();
            aerolinea.CoAerolinea = coAerolinea;
            aerolinea.NoRazonSocial = noRazonSocial;
            return aerolinea;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CoAerolinea
        {
            get
            {
                return _CoAerolinea;
            }
            set
            {
                if (_CoAerolinea != value)
                {
                    OnCoAerolineaChanging(value);
                    ReportPropertyChanging("CoAerolinea");
                    _CoAerolinea = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CoAerolinea");
                    OnCoAerolineaChanged();
                }
            }
        }
        private global::System.String _CoAerolinea;
        partial void OnCoAerolineaChanging(global::System.String value);
        partial void OnCoAerolineaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NoRazonSocial
        {
            get
            {
                return _NoRazonSocial;
            }
            set
            {
                OnNoRazonSocialChanging(value);
                ReportPropertyChanging("NoRazonSocial");
                _NoRazonSocial = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NoRazonSocial");
                OnNoRazonSocialChanged();
            }
        }
        private global::System.String _NoRazonSocial;
        partial void OnNoRazonSocialChanging(global::System.String value);
        partial void OnNoRazonSocialChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_DSDModel", "FK_Vuelo_Aerolinea", "Vuelo")]
        public EntityCollection<Vuelo> Vueloes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Vuelo>("BD_DSDModel.FK_Vuelo_Aerolinea", "Vuelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Vuelo>("BD_DSDModel.FK_Vuelo_Aerolinea", "Vuelo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_DSDModel", Name="Ciudad")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ciudad : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Ciudad.
        /// </summary>
        /// <param name="coCiudad">Valor inicial de la propiedad CoCiudad.</param>
        /// <param name="noDescripcion">Valor inicial de la propiedad NoDescripcion.</param>
        /// <param name="coTipoUbig">Valor inicial de la propiedad CoTipoUbig.</param>
        public static Ciudad CreateCiudad(global::System.String coCiudad, global::System.String noDescripcion, global::System.String coTipoUbig)
        {
            Ciudad ciudad = new Ciudad();
            ciudad.CoCiudad = coCiudad;
            ciudad.NoDescripcion = noDescripcion;
            ciudad.CoTipoUbig = coTipoUbig;
            return ciudad;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CoCiudad
        {
            get
            {
                return _CoCiudad;
            }
            set
            {
                if (_CoCiudad != value)
                {
                    OnCoCiudadChanging(value);
                    ReportPropertyChanging("CoCiudad");
                    _CoCiudad = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CoCiudad");
                    OnCoCiudadChanged();
                }
            }
        }
        private global::System.String _CoCiudad;
        partial void OnCoCiudadChanging(global::System.String value);
        partial void OnCoCiudadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NoDescripcion
        {
            get
            {
                return _NoDescripcion;
            }
            set
            {
                OnNoDescripcionChanging(value);
                ReportPropertyChanging("NoDescripcion");
                _NoDescripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NoDescripcion");
                OnNoDescripcionChanged();
            }
        }
        private global::System.String _NoDescripcion;
        partial void OnNoDescripcionChanging(global::System.String value);
        partial void OnNoDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CoTipoUbig
        {
            get
            {
                return _CoTipoUbig;
            }
            set
            {
                OnCoTipoUbigChanging(value);
                ReportPropertyChanging("CoTipoUbig");
                _CoTipoUbig = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CoTipoUbig");
                OnCoTipoUbigChanged();
            }
        }
        private global::System.String _CoTipoUbig;
        partial void OnCoTipoUbigChanging(global::System.String value);
        partial void OnCoTipoUbigChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CoPais
        {
            get
            {
                return _CoPais;
            }
            set
            {
                OnCoPaisChanging(value);
                ReportPropertyChanging("CoPais");
                _CoPais = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CoPais");
                OnCoPaisChanged();
            }
        }
        private global::System.String _CoPais;
        partial void OnCoPaisChanging(global::System.String value);
        partial void OnCoPaisChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_DSDModel", "FK_Vuelo_Ciudad", "Vuelo")]
        public EntityCollection<Vuelo> Vueloes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Vuelo>("BD_DSDModel.FK_Vuelo_Ciudad", "Vuelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Vuelo>("BD_DSDModel.FK_Vuelo_Ciudad", "Vuelo", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_DSDModel", "FK_Vuelo_Ciudad2", "Vuelo")]
        public EntityCollection<Vuelo> Vueloes1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Vuelo>("BD_DSDModel.FK_Vuelo_Ciudad2", "Vuelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Vuelo>("BD_DSDModel.FK_Vuelo_Ciudad2", "Vuelo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_DSDModel", Name="Vuelo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vuelo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Vuelo.
        /// </summary>
        /// <param name="nuVuelo">Valor inicial de la propiedad NuVuelo.</param>
        /// <param name="coAerolinea">Valor inicial de la propiedad CoAerolinea.</param>
        /// <param name="coCiudadOri">Valor inicial de la propiedad CoCiudadOri.</param>
        /// <param name="coCiudadDes">Valor inicial de la propiedad CoCiudadDes.</param>
        /// <param name="ssCosto">Valor inicial de la propiedad SsCosto.</param>
        /// <param name="qtDisponible">Valor inicial de la propiedad QtDisponible.</param>
        public static Vuelo CreateVuelo(global::System.Int32 nuVuelo, global::System.String coAerolinea, global::System.String coCiudadOri, global::System.String coCiudadDes, global::System.Decimal ssCosto, global::System.Int16 qtDisponible)
        {
            Vuelo vuelo = new Vuelo();
            vuelo.NuVuelo = nuVuelo;
            vuelo.CoAerolinea = coAerolinea;
            vuelo.CoCiudadOri = coCiudadOri;
            vuelo.CoCiudadDes = coCiudadDes;
            vuelo.SsCosto = ssCosto;
            vuelo.QtDisponible = qtDisponible;
            return vuelo;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NuVuelo
        {
            get
            {
                return _NuVuelo;
            }
            set
            {
                if (_NuVuelo != value)
                {
                    OnNuVueloChanging(value);
                    ReportPropertyChanging("NuVuelo");
                    _NuVuelo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NuVuelo");
                    OnNuVueloChanged();
                }
            }
        }
        private global::System.Int32 _NuVuelo;
        partial void OnNuVueloChanging(global::System.Int32 value);
        partial void OnNuVueloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CoAerolinea
        {
            get
            {
                return _CoAerolinea;
            }
            set
            {
                OnCoAerolineaChanging(value);
                ReportPropertyChanging("CoAerolinea");
                _CoAerolinea = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CoAerolinea");
                OnCoAerolineaChanged();
            }
        }
        private global::System.String _CoAerolinea;
        partial void OnCoAerolineaChanging(global::System.String value);
        partial void OnCoAerolineaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CoCiudadOri
        {
            get
            {
                return _CoCiudadOri;
            }
            set
            {
                OnCoCiudadOriChanging(value);
                ReportPropertyChanging("CoCiudadOri");
                _CoCiudadOri = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CoCiudadOri");
                OnCoCiudadOriChanged();
            }
        }
        private global::System.String _CoCiudadOri;
        partial void OnCoCiudadOriChanging(global::System.String value);
        partial void OnCoCiudadOriChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CoCiudadDes
        {
            get
            {
                return _CoCiudadDes;
            }
            set
            {
                OnCoCiudadDesChanging(value);
                ReportPropertyChanging("CoCiudadDes");
                _CoCiudadDes = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CoCiudadDes");
                OnCoCiudadDesChanged();
            }
        }
        private global::System.String _CoCiudadDes;
        partial void OnCoCiudadDesChanging(global::System.String value);
        partial void OnCoCiudadDesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SsCosto
        {
            get
            {
                return _SsCosto;
            }
            set
            {
                OnSsCostoChanging(value);
                ReportPropertyChanging("SsCosto");
                _SsCosto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SsCosto");
                OnSsCostoChanged();
            }
        }
        private global::System.Decimal _SsCosto;
        partial void OnSsCostoChanging(global::System.Decimal value);
        partial void OnSsCostoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FeSalida
        {
            get
            {
                return _FeSalida;
            }
            set
            {
                OnFeSalidaChanging(value);
                ReportPropertyChanging("FeSalida");
                _FeSalida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FeSalida");
                OnFeSalidaChanged();
            }
        }
        private Nullable<global::System.DateTime> _FeSalida;
        partial void OnFeSalidaChanging(Nullable<global::System.DateTime> value);
        partial void OnFeSalidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FeRetorno
        {
            get
            {
                return _FeRetorno;
            }
            set
            {
                OnFeRetornoChanging(value);
                ReportPropertyChanging("FeRetorno");
                _FeRetorno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FeRetorno");
                OnFeRetornoChanged();
            }
        }
        private Nullable<global::System.DateTime> _FeRetorno;
        partial void OnFeRetornoChanging(Nullable<global::System.DateTime> value);
        partial void OnFeRetornoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> HrSalida
        {
            get
            {
                return _HrSalida;
            }
            set
            {
                OnHrSalidaChanging(value);
                ReportPropertyChanging("HrSalida");
                _HrSalida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HrSalida");
                OnHrSalidaChanged();
            }
        }
        private Nullable<global::System.DateTime> _HrSalida;
        partial void OnHrSalidaChanging(Nullable<global::System.DateTime> value);
        partial void OnHrSalidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> HrRetorno
        {
            get
            {
                return _HrRetorno;
            }
            set
            {
                OnHrRetornoChanging(value);
                ReportPropertyChanging("HrRetorno");
                _HrRetorno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HrRetorno");
                OnHrRetornoChanged();
            }
        }
        private Nullable<global::System.DateTime> _HrRetorno;
        partial void OnHrRetornoChanging(Nullable<global::System.DateTime> value);
        partial void OnHrRetornoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 QtDisponible
        {
            get
            {
                return _QtDisponible;
            }
            set
            {
                OnQtDisponibleChanging(value);
                ReportPropertyChanging("QtDisponible");
                _QtDisponible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QtDisponible");
                OnQtDisponibleChanged();
            }
        }
        private global::System.Int16 _QtDisponible;
        partial void OnQtDisponibleChanging(global::System.Int16 value);
        partial void OnQtDisponibleChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_DSDModel", "FK_Vuelo_Aerolinea", "Aerolinea")]
        public Aerolinea Aerolinea
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Aerolinea>("BD_DSDModel.FK_Vuelo_Aerolinea", "Aerolinea").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Aerolinea>("BD_DSDModel.FK_Vuelo_Aerolinea", "Aerolinea").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Aerolinea> AerolineaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Aerolinea>("BD_DSDModel.FK_Vuelo_Aerolinea", "Aerolinea");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Aerolinea>("BD_DSDModel.FK_Vuelo_Aerolinea", "Aerolinea", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_DSDModel", "FK_Vuelo_Ciudad", "Ciudad")]
        public Ciudad Ciudad
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ciudad>("BD_DSDModel.FK_Vuelo_Ciudad", "Ciudad").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ciudad>("BD_DSDModel.FK_Vuelo_Ciudad", "Ciudad").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ciudad> CiudadReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ciudad>("BD_DSDModel.FK_Vuelo_Ciudad", "Ciudad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ciudad>("BD_DSDModel.FK_Vuelo_Ciudad", "Ciudad", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_DSDModel", "FK_Vuelo_Ciudad2", "Ciudad")]
        public Ciudad Ciudad1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ciudad>("BD_DSDModel.FK_Vuelo_Ciudad2", "Ciudad").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ciudad>("BD_DSDModel.FK_Vuelo_Ciudad2", "Ciudad").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ciudad> Ciudad1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ciudad>("BD_DSDModel.FK_Vuelo_Ciudad2", "Ciudad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ciudad>("BD_DSDModel.FK_Vuelo_Ciudad2", "Ciudad", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
